name = "hush"
license = "GPLv3"
licenselink = "https://github.com/tseujingyu/rimu/blob/wending/LICENSE"
description = "hugo+bash=hush"
homepage = "https://jingyu.red/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Jingyu"
  homepage = "https://jingyu.red"
